sonar.projectKey=AgroSmart-Backend
sonar.projectName=AgroSmart-Backend
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.host.url=http://localhost:9000
sonar.token=sqp_c36d2c844830f0424c64c6f3299f93b978874575